{% set name = "portend" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 600dd54175e17e9347e5f3d4217aa8bcf4bf4fa5ffbc4df034e5ec1ba7cdaff5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - tempora >=1.8

test:
  imports:
    - portend

about:
  home: https://github.com/jaraco/portend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TCP port monitoring utilities
  dev_url: https://github.com/jaraco/portend

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
