{% set name = "portend" %}
{% set version = "2.6" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "600dd54175e17e9347e5f3d4217aa8bcf4bf4fa5ffbc4df034e5ec1ba7cdaff5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python
    - tempora >=1.8

test:
  imports:
    - portend

about:
  home: https://github.com/jaraco/portend
  # license_file: No license or manifest - see https://github.com/jaraco/portend/issues/3
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: TCP port monitoring utilities
  dev_url: https://github.com/jaraco/portend

extra:
  recipe-maintainers:
    - pmlandwehr
