{% set name = "portend" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac0e57ae557f75dc47467579980af152e8f60bc2139547eff8469777d9110379

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python >=3.6
    - tempora >=1.8

test:
  imports:
    - portend

about:
  home: https://github.com/jaraco/portend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TCP port monitoring utilities
  dev_url: https://github.com/jaraco/portend

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
