travis:
  secure:
    BINSTAR_TOKEN: sLdpc7Kv6kClQ/IRpJE382X5wFktnCKvTBpxFUpVK3Tfk/rjr9PfMoP7lY2VLmITQnyZOyRtfX8iUl1ZXVQmTiu/S3x9t0HcF0H2mh4ZhT2tXty4xfqTd2UkoCghuDZe4E5EQrI0vgCSErhN9peYsaDzzqdlRR2Wc76pAXNtnYe5Z5JwzqCwlKjXO7pdG4d0rTuo4wfZOVNXD1bbKZRSj+05ogIXHqYF+QnDC8yX1h2vp/Ck+HDCJko2ByzrCC9yayMlfvIUYiCgl3UJMalA5JQ2m7p0QI9P/RX4HRc+ka8fvNbaGHPjcAfjzH4tk4cFkN3h6so2KzpwwV8lfPouXmbkVhOLNH/3jFs7XiqnKFkKrNkAsxMidShgk7yiXWrwOTkJGYxrr/Jvzww4u/etZYtSjeppoeN+Im5hNVPL0P2NLyJOZCY+Lv+U/7hT3c1/b860DvcGYzDXF8hP9rC3iHVATUFt28a4j8XlRVg8204c3ZAhJKqsmPlPoSvpoaK+GQ7+d9sdT6xVDY6vIXCpxvnL1z3WhI4UXjy0Lgc+S9RNdLVZVt4/LTnWi7SvmgUw4N7Hfme+U/d0bkfEnTHevR6x4wc52twnNq52iHUxq9WVLkKbk0avPnZwQt1R+QnL4Y2QQUfkyatjp8M3DR9ySY5NXzQD1BH7lKSrx4OwAP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
